Intro
tomsbzbrs/codelex_csharp_exercises pull request #1
Opened 2022-07-26 10:16 UTC by tomsbzbrs

I'm sorry for the previous pushes/requests, I had a few problems that surfaced only after issuing the pull request. This is the final version.

2022-07-26 18:04 UTC, ausmoons requested changes

2022-07-26 18:04 UTC, ausmoons commented on Exercises/Basics/AddNumbers-01/Program.cs
> +        static int AddNumbers(int a, int b, int c)
Tev kkas nav ar gitignore. Te ir .vs faili un man lokāli arī pievienojas lieki faili

2022-07-26 18:04 UTC, ausmoons commented on Exercises/Basics/AddNumbers-01/Program.cs
> +
Lieka tukša rinda

2022-07-27 09:27 UTC, tomsbzbrs commented on Exercises/Basics/AddNumbers-01/Program.cs
> +        static int AddNumbers(int a, int b, int c)
ok, meklēju

2022-07-27 20:09 UTC, ausmoons approved these changes
Sakārto gitignore mainā

2022-07-28 06:04 UTC, tomsbzbrs commented on Exercises/Basics/AddNumbers-01/Program.cs
> +
izlabots

2022-07-28 06:09 UTC, merged