added completed exercises ClassesAndObjects
tomsbzbrs/codelex_csharp_exercises pull request #11
Opened 2022-08-15 05:55 UTC by tomsbzbrs

Iesniedzu mājasdarbu mapi: ClassesAndObjects

2022-08-15 19:19 UTC, ausmoons requested changes

2022-08-15 19:19 UTC, ausmoons commented on Exercises/ClassesAndObjects/ClassesAndObjects/Account/Account.cs
> +
?

2022-08-15 19:19 UTC, ausmoons commented on Exercises/ClassesAndObjects/ClassesAndObjects/Account/Account.cs
> +
?

2022-08-15 19:19 UTC, ausmoons commented on Exercises/ClassesAndObjects/ClassesAndObjects/Account/Program.cs
> +        {
?

2022-08-15 19:19 UTC, ausmoons commented on Exercises/ClassesAndObjects/ClassesAndObjects/BankAccount/Program.cs
> +        {
?

2022-08-15 19:19 UTC, ausmoons commented on Exercises/ClassesAndObjects/ClassesAndObjects/EnergyDrinks/Program.cs
> +             Console.WriteLine("Approximately " + energyDrinkers + " bought at least one energy drink");
?

2022-08-15 19:19 UTC, ausmoons commented on Exercises/ClassesAndObjects/ClassesAndObjects/EnergyDrinks/Program.cs
> +        }
?

2022-08-15 19:19 UTC, ausmoons commented on Exercises/ClassesAndObjects/ClassesAndObjects/Exercise_1/Product.cs
> +        public string name;
Ja public tad ar lielo burtu, vai arī te vajag private?

2022-08-15 19:19 UTC, ausmoons commented on Exercises/ClassesAndObjects/ClassesAndObjects/FuelConsumptionCalculator/Program.cs
> +            } else if(userChoice == 2)
Else if jaunā rindā

2022-08-15 19:19 UTC, ausmoons commented on Exercises/ClassesAndObjects/ClassesAndObjects/FuelConsumptionCalculator/Program.cs
> +            } else if(userChoice == 2)
Else if jaunā rindā

2022-08-15 19:19 UTC, ausmoons commented on Exercises/ClassesAndObjects/ClassesAndObjects/VideoStore/Video.cs
> +        {
?

2022-08-15 19:19 UTC, ausmoons commented on Exercises/ClassesAndObjects/ClassesAndObjects/VideoStore/VideoStore.cs
> +
?

2022-08-15 19:19 UTC, ausmoons commented on Exercises/ClassesAndObjects/EnergyDrinks/Program.cs
> +            energyDrinkers = Convert.ToInt32(_NumberedSurveyed * _PurchasedEnergyDrinks);
Var uzreiz return

2022-08-15 19:19 UTC, ausmoons commented on Exercises/ClassesAndObjects/Exercise_1/Product.cs
> +        public double priceAtStart;
Private?

2022-08-15 19:19 UTC, ausmoons commented on Exercises/ClassesAndObjects/Exercise_1/Program.cs
> +
Lieka tukša rinda

2022-08-15 19:19 UTC, ausmoons commented on Exercises/ClassesAndObjects/Exercise_12/Student.cs
> +            TestsTaken = testsTaken;
Te izmantotu _testsTaken

2022-08-15 19:19 UTC, ausmoons commented on Exercises/ClassesAndObjects/Exercise_13/Smoothie.cs
> +
Pārbaudi visur liekās tukšās rindas

2022-08-15 19:19 UTC, ausmoons commented on Exercises/ClassesAndObjects/Exercise_14/Program.cs
> +        public int month;
Katrā klase savā failā. Private?

2022-08-15 19:19 UTC, ausmoons commented on Exercises/ClassesAndObjects/Exercise_7/SavingsAccount.cs
> +            WithdrawalsTotal += userWithdrawal;
Šeit visur iekšā būtu jāizmanto private

2022-08-15 19:19 UTC, ausmoons commented on Exercises/ClassesAndObjects/FuelConsumptionCalculator/Program.cs
> +            } else if(userChoice == 2)
Else of jaunā rindā

2022-08-15 19:19 UTC, ausmoons commented on Exercises/ClassesAndObjects/VideoStore/VideoStoreTest.cs
> +
Lieka tukša rinda

2022-08-16 05:53 UTC, tomsbzbrs commented on Exercises/ClassesAndObjects/ClassesAndObjects/Account/Account.cs
> +
Man kaut kas nepareizi iecommitojies, laboju.

2022-08-16 05:54 UTC, tomsbzbrs commented on Exercises/ClassesAndObjects/ClassesAndObjects/EnergyDrinks/Program.cs
> +             Console.WriteLine("Approximately " + energyDrinkers + " bought at least one energy drink");
Šeit arī kaut kas nogājis greizi.

2022-08-16 06:01 UTC, tomsbzbrs commented on Exercises/ClassesAndObjects/Exercise_14/Program.cs
> +        public int month;
Izlaboju. Sapratu, ka nav obligāti atsevišķi.

2022-08-16 06:06 UTC, tomsbzbrs commented on Exercises/ClassesAndObjects/Exercise_7/SavingsAccount.cs
> +            WithdrawalsTotal += userWithdrawal;
Izlaboju.

2022-08-16 06:07 UTC, tomsbzbrs commented on Exercises/ClassesAndObjects/FuelConsumptionCalculator/Program.cs
> +            } else if(userChoice == 2)
Izlaboju.

2022-08-16 06:08 UTC, tomsbzbrs commented on Exercises/ClassesAndObjects/VideoStore/VideoStoreTest.cs
> +
Izlabots.

2022-08-16 06:10 UTC, tomsbzbrs commented on Exercises/ClassesAndObjects/ClassesAndObjects/BankAccount/Program.cs
> +        {
Nesaprotu, kas šeit jāmaina - Access nepareizs?

2022-08-16 06:11 UTC, tomsbzbrs commented on Exercises/ClassesAndObjects/ClassesAndObjects/Account/Program.cs
> +        {
Izlabots.

2022-08-16 06:13 UTC, tomsbzbrs commented on Exercises/ClassesAndObjects/Exercise_13/Smoothie.cs
> +
Izlaboju!

2022-08-16 06:14 UTC, tomsbzbrs commented on Exercises/ClassesAndObjects/ClassesAndObjects/Account/Account.cs
> +
Nepareizais commits.

2022-08-16 06:24 UTC, tomsbzbrs commented on Exercises/ClassesAndObjects/ClassesAndObjects/EnergyDrinks/Program.cs
> +        }
Arī kaut kas nepareizi aizgājis, tagad vajadzētu būt ok.

2022-08-16 06:27 UTC, tomsbzbrs commented on Exercises/ClassesAndObjects/ClassesAndObjects/Exercise_1/Product.cs
> +        public string name;
Izlabots.

2022-08-16 06:29 UTC, tomsbzbrs commented on Exercises/ClassesAndObjects/ClassesAndObjects/FuelConsumptionCalculator/Program.cs
> +            } else if(userChoice == 2)
Izlabots.

2022-08-16 06:30 UTC, tomsbzbrs commented on Exercises/ClassesAndObjects/ClassesAndObjects/FuelConsumptionCalculator/Program.cs
> +            } else if(userChoice == 2)
Laboju.

2022-08-16 06:31 UTC, tomsbzbrs commented on Exercises/ClassesAndObjects/EnergyDrinks/Program.cs
> +            energyDrinkers = Convert.ToInt32(_NumberedSurveyed * _PurchasedEnergyDrinks);
Izlaboju visiem.

2022-08-16 06:32 UTC, tomsbzbrs commented on Exercises/ClassesAndObjects/Exercise_1/Product.cs
> +        public double priceAtStart;
Pāpratu uzdevuma nosacījumus, izlaboju!

2022-08-16 06:32 UTC, tomsbzbrs commented on Exercises/ClassesAndObjects/Exercise_1/Program.cs
> +
Izlabots.

2022-08-16 06:52 UTC, tomsbzbrs commented on Exercises/ClassesAndObjects/ClassesAndObjects/VideoStore/VideoStore.cs
> +
Kaut kas nogājis greizi

2022-08-16 06:52 UTC, tomsbzbrs commented on Exercises/ClassesAndObjects/Exercise_12/Student.cs
> +            TestsTaken = testsTaken;
Izlaboju!

2022-08-16 19:07 UTC, ausmoons requested changes

2022-08-16 19:07 UTC, ausmoons commented on Exercises/ClassesAndObjects/ClassesAndObjects/Account/Account.cs
> +
Te vel joprojam radas tuksas metodes

2022-08-16 19:07 UTC, ausmoons commented on Exercises/ClassesAndObjects/ClassesAndObjects/Account/Program.cs
> +        {
Vel joprojam tuksa klase

2022-08-16 19:07 UTC, ausmoons commented on Exercises/ClassesAndObjects/ClassesAndObjects/BankAccount/Program.cs
> +        {
Tagad te ir tikai tuksa metode

2022-08-16 19:07 UTC, ausmoons commented on Exercises/ClassesAndObjects/ClassesAndObjects/EnergyDrinks/Program.cs
> +             Console.WriteLine("Approximately " + energyDrinkers + " bought at least one energy drink");
Neredzu labojumus

2022-08-16 19:07 UTC, ausmoons commented on Exercises/ClassesAndObjects/ClassesAndObjects/VideoStore/VideoStore.cs
> +
Nav labojumu

2022-08-17 06:46 UTC, closed without merging