Collections
tomsbzbrs/codelex_csharp_exercises pull request #19
Opened 2022-08-19 12:39 UTC by tomsbzbrs

Iesniedzu mājasdarbu mapi: Collections.

2022-08-19 17:15 UTC, ausmoons requested changes

2022-08-19 17:15 UTC, ausmoons commented on Exercises/Collections/Exercise5/Program.cs
> +        static bool IsNumberHappy(int number)
Starp metodēm tukša rinda

2022-08-19 17:15 UTC, ausmoons commented on Exercises/Collections/FlightPlanner/Program.cs
> +                if (city == "Honolulu" && y == "Honolulu")
Kas te notiek? Tu izpildi vien un to pašu, tad tā loģika var būt kopā.

2022-08-19 17:15 UTC, ausmoons commented on Exercises/Collections/Histogram/Program.cs
> +        static void DisplayScoreChart(Dictionary<string, string> scores)
Starp metodēm tukša rinda

2022-08-20 09:05 UTC, tomsbzbrs commented on Exercises/Collections/Histogram/Program.cs
> +        static void DisplayScoreChart(Dictionary<string, string> scores)
Izlaboju.

2022-08-20 09:06 UTC, tomsbzbrs commented on Exercises/Collections/Exercise5/Program.cs
> +        static bool IsNumberHappy(int number)
Izlaboju.

2022-08-20 09:11 UTC, tomsbzbrs commented on Exercises/Collections/FlightPlanner/Program.cs
> +                if (city == "Honolulu" && y == "Honolulu")
Izlaboju.

2022-08-21 17:43 UTC, ausmoons approved these changes

2022-08-22 06:02 UTC, merged