added completed exercises
tomsbzbrs/codelex_csharp_exercises pull request #2
Opened 2022-07-26 10:18 UTC by tomsbzbrs

2022-07-26 18:07 UTC, ausmoons requested changes

2022-07-26 18:07 UTC, ausmoons commented on Exercises/Basics/ConvertCurrency-13/Program.cs
> +            double exchangeRateGBPToUSD = 0.6;
Tev arī PR ir šie faili

2022-07-26 18:07 UTC, ausmoons commented on Exercises/Basics/ConvertCurrency-14/Program.cs
> +            double exchangeRateGBPToUSD = 1.4;
Lieki bin, obj faili

2022-07-26 18:07 UTC, ausmoons commented on Exercises/Basics/ConvertCurrency-14/Program.cs
>          //change this method accordingly
Lieks komentārs

2022-07-27 09:19 UTC, tomsbzbrs commented on Exercises/Basics/ConvertCurrency-14/Program.cs
>          //change this method accordingly
aha, tad tos uzdevuma komentus var dzēst ārā?

2022-07-27 09:24 UTC, tomsbzbrs commented on Exercises/Basics/ConvertCurrency-14/Program.cs
> +            double exchangeRateGBPToUSD = 1.4;
> Lieki bin, obj faili

tad nedaudz jāizmaina .gitignore fails, lai tie faili nenāktu, ja?

2022-07-27 20:01 UTC, ausmoons commented on Exercises/Basics/ConvertCurrency-14/Program.cs
> +            double exchangeRateGBPToUSD = 1.4;
Tu biji tos jau ielicis main, no main bija jāizņem, bet ok

2022-07-27 20:01 UTC, ausmoons commented on Exercises/Basics/ConvertCurrency-14/Program.cs
>          //change this method accordingly
jā

2022-07-27 20:05 UTC, ausmoons requested changes

2022-07-27 20:05 UTC, ausmoons commented on .gitignore
> -*.log
git fails ir jālabo main vai atsevišķā branchā, bet tad tikai priekš gitignore faila.

2022-07-27 20:05 UTC, ausmoons commented on Exercises/Intro/SymmetricalNumber/obj/Debug/net5.0/SymmetricalNumber.GeneratedMSBuildEditorConfig.editorconfig
> +build_property.ProjectDir = C:\Users\panch\Desktop\codelex_csharp_exercises\Exercises\Intro\SymmetricalNumber\
Pašlaik šis obj fails te tiek pievienots. Ieliec mainā gitignore failu un tad izmaiņas ievelc šeit. Liekos failus manuāli izdzēs

2022-07-28 05:19 UTC, tomsbzbrs commented on Exercises/Intro/SymmetricalNumber/obj/Debug/net5.0/SymmetricalNumber.GeneratedMSBuildEditorConfig.editorconfig
> +build_property.ProjectDir = C:\Users\panch\Desktop\codelex_csharp_exercises\Exercises\Intro\SymmetricalNumber\
ok, sapratu

2022-07-28 05:59 UTC, tomsbzbrs commented on Exercises/Intro/SymmetricalNumber/obj/Debug/net5.0/SymmetricalNumber.GeneratedMSBuildEditorConfig.editorconfig
> +build_property.ProjectDir = C:\Users\panch\Desktop\codelex_csharp_exercises\Exercises\Intro\SymmetricalNumber\
es it kā to izdarīju, tikko atkārtoju šīs darbības vēl vienu reizi

2022-07-28 06:22 UTC, tomsbzbrs commented on Exercises/Basics/ConvertCurrency-14/Program.cs
> +            double exchangeRateGBPToUSD = 1.4;
Tagad visam vajadzētu būt ok(?).

2022-07-28 14:46 UTC, ausmoons approved these changes

2022-07-28 17:02 UTC, merged