gitinit
tomsbzbrs/codelex_csharp_exercises pull request #20
Opened 2022-08-24 16:43 UTC by tomsbzbrs

Iesniedzu mājasdarbu mapi - Polymorphism.

2022-08-26 07:33 UTC, ausmoons requested changes

2022-08-26 07:33 UTC, ausmoons commented on Exercises/Polymorphism/AdApp/Poster.cs
> +        public override string ToString()
Starp metodēm tukša rinda

2022-08-26 07:33 UTC, ausmoons commented on Exercises/Polymorphism/DragRace/Audi.cs
> +        public string Name
Starp metodēm tukša rinda

2022-08-26 07:33 UTC, ausmoons commented on Exercises/Polymorphism/Hierarchy/Cat.cs
> +        public Cat(string animalName, string animalType, string breed, double animalWeight, string livingRegion, int foodEaten) : base(animalName, animalType, animalWeight, livingRegion, foodEaten)
Sākot no : base loģiku pārnest jaunā rindā

2022-08-26 07:33 UTC, ausmoons commented on Exercises/Polymorphism/Hierarchy/Mouse.cs
> +        public override void makeSound()
Metodes ar lielo burtu

2022-08-26 07:33 UTC, ausmoons commented on Exercises/Polymorphism/Hierarchy/Tiger.cs
> +        public Tiger(string animalName, string animalType, double animalWeight, string livingRegion, int foodEaten) : base(animalName, animalType, animalWeight, livingRegion, foodEaten)
Sākot no : base jaunā rindā

2022-08-26 07:33 UTC, ausmoons commented on Exercises/Polymorphism/Hierarchy/Zebra.cs
> +        public Zebra(string animalName, string animalType, double animalWeight, string livingRegion, int foodEaten) : base(animalName, animalType, animalWeight, livingRegion, foodEaten)
: base jaunā rindā

2022-08-26 07:33 UTC, ausmoons commented on Exercises/Polymorphism/VendingMachine/Program.cs
> +            bool isAccepted = acceptedNominals.Contains(receivedNominal);
te var uzreiz return, jo isAccepted netiek tālāk izmantots

2022-08-26 09:40 UTC, tomsbzbrs commented on Exercises/Polymorphism/AdApp/Poster.cs
> +        public override string ToString()
Izlabots.

2022-08-26 09:40 UTC, tomsbzbrs commented on Exercises/Polymorphism/DragRace/Audi.cs
> +        public string Name
Izlabots.

2022-08-26 09:42 UTC, tomsbzbrs commented on Exercises/Polymorphism/Hierarchy/Cat.cs
> +        public Cat(string animalName, string animalType, string breed, double animalWeight, string livingRegion, int foodEaten) : base(animalName, animalType, animalWeight, livingRegion, foodEaten)
To pašu base konstruktora rindu? Ja jā, izlabots.

2022-08-26 09:43 UTC, tomsbzbrs commented on Exercises/Polymorphism/Hierarchy/Mouse.cs
> +        public override void makeSound()
Izlabots visur.

2022-08-26 09:45 UTC, tomsbzbrs commented on Exercises/Polymorphism/Hierarchy/Zebra.cs
> +        public Zebra(string animalName, string animalType, double animalWeight, string livingRegion, int foodEaten) : base(animalName, animalType, animalWeight, livingRegion, foodEaten)
Izlabots.

2022-08-26 09:45 UTC, tomsbzbrs commented on Exercises/Polymorphism/Hierarchy/Tiger.cs
> +        public Tiger(string animalName, string animalType, double animalWeight, string livingRegion, int foodEaten) : base(animalName, animalType, animalWeight, livingRegion, foodEaten)
Izlabots visur.

2022-08-26 09:45 UTC, tomsbzbrs commented on Exercises/Polymorphism/VendingMachine/Program.cs
> +            bool isAccepted = acceptedNominals.Contains(receivedNominal);
Izlabots.

2022-08-28 07:52 UTC, ausmoons approved these changes

2022-08-28 07:52 UTC, ausmoons commented on Exercises/Polymorphism/Hierarchy/Zebra.cs
> +        : base(animalName, animalType, animalWeight, livingRegion, foodEaten)
Te būtu jābūt vienam tab, ja nu kas

2022-08-30 06:37 UTC, merged