Types and variables
tomsbzbrs/codelex_csharp_exercises pull request #6
Opened 2022-07-30 16:03 UTC by tomsbzbrs

Uztaisīju jaunu PR, kurā beidzot viss ir apdeitots;

Uztaisīju reset:
-tagad MAIN branch/TypesAndVariables ir tukšs;
-tagad MAIN branch/Arithmetic ir tukšs;
-izpildītais Arithmetic folderis šajā branchā vairs nav;
-tagad TypesAndVariables ir izpildīts tikai šajā branch;
-nekas izņemot akceptēto nav mērdžots;

Ceru, ka viss ok;

2022-07-30 20:23 UTC, ausmoons requested changes

2022-07-30 20:23 UTC, ausmoons commented on Exercises/Arithmetic/SumAverageRunningInt/Program.cs
>          {
Tu gribi pilnībā izdzēst šos failus no main ?
![image](https://user-images.githubusercontent.com/53189160/181994993-46289879-0b3d-49ae-a627-c97c344e6536.png)

2022-07-30 20:23 UTC, ausmoons commented on Exercises/TypesAndVariables/Exercise_4/Program.cs
> +        }
Starp metodēm vajag tukšu rindu

2022-07-30 20:23 UTC, ausmoons commented on Exercises/TypesAndVariables/Exercise_5/Program.cs
> +        static void LinePrinter()
Starp metodēm vajag tukšu rindu

2022-07-31 06:16 UTC, tomsbzbrs commented on Exercises/Arithmetic/SumAverageRunningInt/Program.cs
>          {
Jā, šie faili tika nejauši pievienoti.

2022-07-31 06:18 UTC, tomsbzbrs commented on Exercises/TypesAndVariables/Exercise_5/Program.cs
> +        static void LinePrinter()
Ok, laboju visam, kam trūkst. Šķita, ka tādos gadījumos VS automātiski ieliek tukšu rindu.

2022-07-31 06:18 UTC, tomsbzbrs commented on Exercises/TypesAndVariables/Exercise_4/Program.cs
> +        }
Ok, laboju.

2022-07-31 09:46 UTC, ausmoons approved these changes

2022-07-31 09:53 UTC, merged