first commit with completed Arithmetic exercises
tomsbzbrs/codelex_csharp_exercises pull request #7
Opened 2022-07-31 15:48 UTC by tomsbzbrs

Iesniedzu mājasdarbu mapi: Arithmetic.

2022-07-31 20:14 UTC, ausmoons requested changes

2022-07-31 20:14 UTC, ausmoons commented on Exercises/Arithmetic/CalculatorBMI/Program.cs
> +                return $"Your Body Mass Index is {userBMI}, you are overweight.";
Kur būs 18.5?

2022-07-31 20:14 UTC, ausmoons commented on Exercises/Arithmetic/TrueIf15/Program.cs
> +                return true;
visus true var likt kopā

2022-08-01 06:30 UTC, tomsbzbrs commented on Exercises/Arithmetic/TrueIf15/Program.cs
> +                return true;
izlaboju

2022-08-01 06:30 UTC, tomsbzbrs commented on Exercises/Arithmetic/CalculatorBMI/Program.cs
> +                return $"Your Body Mass Index is {userBMI}, you are overweight.";
izlaboju

2022-08-01 18:07 UTC, ausmoons approved these changes

2022-08-01 18:07 UTC, ausmoons commented on Exercises/Arithmetic/TrueIf15/Program.cs
> +            bool isThere15 = (inputA == 15 || inputB == 15 || inputA + inputB == 15 || inputA - inputB == 15 || inputB - inputA == 15);
return te varēja uzreiz

2022-08-02 05:55 UTC, tomsbzbrs commented on Exercises/Arithmetic/TrueIf15/Program.cs
> +            bool isThere15 = (inputA == 15 || inputB == 15 || inputA + inputB == 15 || inputA - inputB == 15 || inputB - inputA == 15);
O jā, izlaboju arī!

2022-08-02 05:55 UTC, merged