adding completed exercises:  Arrays
tomsbzbrs/codelex_csharp_exercises pull request #9
Opened 2022-08-06 08:13 UTC by tomsbzbrs

Iesniedzu mājasdarbu mapi - Arrays.

2022-08-06 13:59 UTC, ausmoons requested changes

2022-08-06 13:59 UTC, ausmoons commented on Exercises/Arrays/Arrays/Exercise4/Program.cs
> +            bool isFound = false;
bool default ir false

2022-08-06 13:59 UTC, ausmoons commented on Exercises/Arrays/Arrays/Exercise_10/Program.cs
> +        static int[] CountPositiveNegativeNumbers(int[] arrayToCount)
Starp metodēm vajag tukšu rindu

2022-08-06 13:59 UTC, ausmoons commented on Exercises/Arrays/Arrays/TicTacToe/Program.cs
> +        static bool IsWon()
HasWon

2022-08-06 13:59 UTC, ausmoons commented on Exercises/Arrays/Arrays/TicTacToe/Program.cs
> +                isWon = true;
return uzreiz var būt

2022-08-07 08:26 UTC, tomsbzbrs commented on Exercises/Arrays/Arrays/Exercise4/Program.cs
> +            bool isFound = false;
Izlaboju.

2022-08-07 08:26 UTC, tomsbzbrs commented on Exercises/Arrays/Arrays/Exercise_10/Program.cs
> +        static int[] CountPositiveNegativeNumbers(int[] arrayToCount)
Izlaboju.

2022-08-07 08:27 UTC, tomsbzbrs commented on Exercises/Arrays/Arrays/TicTacToe/Program.cs
> +        static bool IsWon()
Izlaboju.

2022-08-07 08:27 UTC, tomsbzbrs commented on Exercises/Arrays/Arrays/TicTacToe/Program.cs
> +                isWon = true;
Salaboju.

2022-08-07 19:40 UTC, ausmoons approved these changes

2022-08-08 06:12 UTC, merged